vuejs/composition-api

README.md
README.zh-CN.md

去掉 `README.md` 文件中重复的 `Example` 代码

doc: remove README repeat code

---

README.zh-CN.md

fix:modify the typos in the README.zh-CN.md

---

README.md

I believe this was the context you were shooting for in the final paragraphs.

Updated README.md - Grammatical fixes

---

src/apis/watch.ts
src/component/componentProps.ts
src/reactivity/reactive.ts
src/reactivity/ref.ts
src/reactivity/set.ts
src/setup.ts
src/symbols.ts
test/apis/watch.spec.js
test/setup.spec.js

Typos and remove unnecessary `as any`

fix typos and removing couple typescript `as any`

---

README.md
README.zh-CN.md

docs: Fixed example code syntax error

docs: Fixed example code syntax error

---

src/reactivity/set.ts
src/setup.ts

remove some typescript `as any`

---

README.md

correct typos on english readme

Typos on readme english

---

README.md
README.zh-CN.md

docs: fix format

---

src/utils.ts

fix: correct the symbol check

---

rollup.config.js

fix: __DEV__ is not defined

---

src/setup.ts
test/setup.spec.js

fix https://github.com/vuejs/composition-api/issues/357
marks `props` as reactive

fix: mark props as reactive

---

src/reactivity/reactive.ts
test/setup.spec.js

fix https://github.com/vuejs/composition-api/issues/233

fix(setup): Allow retuning frozen objects on the setup

---

package.json

Let match the code formatting with vue-next :)
I haven't run the prettier for the whole project yet, maybe we can do that until the next release is ready.

chore(prettier): match with vue-next

---

.gitignore
package.json
rollup.config.js
tsconfig.json
yarn.lock

chore: bundle typing into single d.ts file

---

src/component/componentOptions.ts

fix(type): accept undefined return for setup()

---

package.json
src/install.ts
src/runtimeContext.ts

Warn both on package install and plugin install

feat: Vue version warning in dev mode

---

src/reactivity/reactive.ts

fix https://github.com/vuejs/composition-api/issues/440

fix(IE11): `isReactive` add check for `isObject` before `Object.extensible`

---

test/setup.spec.js

close #448, resolve #449
This is not long a bug in the latest implementation. Adding tests by #449.
Co-Authored-By: Carlos Rodrigues <carlos@hypermob.co.uk>

test: add test cases for #448

---

src/reactivity/reactive.ts
test/ssr/ssrReactive.spec.ts

fix(SSR): value set for props, fix #550

---

src/apis/watch.ts
test/apis/watch.spec.js

fix: set default value of flush to 'pre' (fix #565)

---

src/component/componentProps.ts
src/component/componentProxy.ts
test-dts/defineComponent.test-d.ts

Improve prop type infering
Fix #555

fix(types): prop type infer, fix #555

---

README.md
README.zh-CN.md

chore: update jsx docs, close #568

---

src/component/componentProps.ts
src/component/componentProxy.ts

fix(type): vue constructor should not require props with default values

---

CHANGELOG.md

Update CHANGELOG.md of v0.6.0

---

src/component/componentOptions.ts

fix(types): attrs in SetupContext fix#562

---

README.md

https://github.com/vuejs/composition-api/issues/604

docs: update readme about Browser Compatibility

---

src/apis/useCssModule.ts
test/apis/useCssModule.spec.js

Fix useCSSModule to adapt the change of getCurrentInstance and add test for useCSSModule. #620

fix: useCSSModule to adapt the change of getCurrentInstance, close #620

---

src/runtimeContext.ts
src/utils/instance.ts
test/v3/runtime-core/componentProxy.spec.ts

`getCurrentInstance().emit` is not working
also typo on `getCurrentVu2Instance`

fix(getCurrentInstance): emit event

---

README.md
README.zh-CN.md

already support defineAsyncComponent

docs(README): remove outdated(already support defineAsyncComponent)

---

src/apis/computed.ts
src/apis/index.ts
src/reactivity/index.ts

- `ToRefs`
- `ComputedGetter`
- `ComputedSetter`
- `WritableComputedOptions`

fix: update types to algin with vue-next

---

src/component/componentProps.ts
test-dts/defineComponent.test-d.ts
test/types/defineComponent.spec.ts

fix(types): RequiredKeys type

---

src/component/componentProps.ts
test-dts/defineComponent.test-d.ts
test/types/defineComponent.spec.ts

Reverts vuejs/composition-api#655, close #658

Revert "fix(types): RequiredKeys type"

---

src/component/componentProps.ts
test-dts/defineComponent.test-d.ts

fix(types): optional Boolean prop types #636

---

src/utils/utils.ts

fix: Memory leak caused by global variables.

---

src/utils/utils.ts
test/v3/reactivity/del.spec.ts

fix(reactivity): unexpected behaviors for array index out of valid array length when set and del

---

src/reactivity/ref.ts
test/v3/reactivity/ref.spec.ts

fix(proxyRefs): infinite loop when using proxyRefs.

---

src/reactivity/del.ts
src/reactivity/set.ts

fix(types): use AnyObject insteads of any

fix(types): use AnyObject insteads of any

---

src/reactivity/reactive.ts
test/v3/reactivity/reactive.spec.ts

fix: the hasOwn should be used to determine whether an attribute exists.

---

src/reactivity/reactive.ts

Use present participle ('providing' instead of 'provide')

chore: warning message grammar

---

test/v3/reactivity/set.spec.ts

test: add test cases for reactivity/set

test: add test cases for reactivity/set

---

test/v3/runtime-core/useCssModule.spec.ts

test: test for v3 useCssModule

test: test for v3 useCssModule

---

src/mixin.ts
src/reactivity/del.ts
src/reactivity/reactive.ts

refactor: use utils isArray

---

src/apis/lifecycle.ts

chore(type): lifecycle hooks return type

---

src/mixin.ts
test/setup.spec.js

fix(function): properties of function should not disappear.

---

src/apis/effectScope.ts
test/v3/reactivity/effectScope.spec.ts

test(effectScope): add test case for effectScope

---

src/apis/effectScope.ts
test/v3/reactivity/effectScope.spec.ts

fix: typos

---

src/reactivity/reactive.ts
src/reactivity/set.ts
test/ssr/ssrReactive.spec.ts

fix(set): reactive in SSR w/ set

---

src/mixin.ts
test/setup.spec.js
test/setupContext.spec.ts

fix(setup): should not trigger getter w/ object computed nested

---

README.zh-CN.md

docs: update Chinese README

---

src/apis/watch.ts
src/utils/utils.ts

chore(watch): use polyfill instead of object.is

---

README.md
README.zh-CN.md
src/apis/effectScope.ts

update code demo in the README and fix spell

docs: update code demo and code annotation

---

README.md
README.zh-CN.md

ref: https://github.com/badges/shields/issues/8671

docs: fix build status badges error

---

pnpm-lock.yaml
src/apis/inject.ts
src/env.d.ts
src/utils/utils.ts

add inject key types, correct me if I got wrong.

feat: support inject key types
