test/functions/computed.spec.js

In the current version of vue-function-api (2.0.6) if you define a mixin with computed properties usages of `computed()` will break when you have more than one component of a given type (like in a v-for list). The computed properties will return the values from the first component even for all other instances.
The master branch does **not** have this problem (awesome! — do you know when a release will be tagged?) but I thought having an explicit test for this would be useful to ensure no regressions occur.

Add test verifying mixins don't break computed properties

---

README.md

HI!
I just read the README.md documentation and found some visible grammatical errors in the Misc. section. So here's a little PR to fix those grammatical errors.
Thanks!

README.md - fix some grammatical errors

---

src/apis/inject.ts
src/setup.ts
test/apis/inject.spec.js

Since for `provided()` we manually assign to `vm._provided` during `beforeCreate` Vue will overwrite whatever we have set if there's a 2.x API `$options.provide`, which gets assigned to `_provided` *after* `beforeCreate`.
I solved it with a setter.
Because plugins or mixins may add their own provide options, which would then override provides from `setup` 
close #66

fix: provide() should work when combined with 2.x provide syntax

---

README.md
README.zh-CN.md

a missing import found in
[https://github.com/vuejs/vue-function-api#typescript](https://github.com/vuejs/vue-function-api#typescript)

fix: README.md #typescript missing import

---

src/setup.ts
test/setupContext.spec.js

close #128, #132
so far missing tests

[WIP] feat: expose listeners on context

---

src/install.ts

Hey liximomo, I've been learning your implementations of new Vue.js RFCs, and I thought it is a really awesome way to provide a new feature on old Vue.js architecture.
But I've found in your `src/install.ts` when provided a duplicate if condition of `!isRef(toVal)`.
I guess it should be `!isRef(fromVal)`, was it a correct fix?

fix(src/install.ts): fix possible if-condition mistakes

---

README.md
README.zh-CN.md

Currently using `reactive` will change the original object passed to the function, this is not an expected behaviour, since the [doc](https://vue-composition-api-rfc.netlify.com/api.html#reactive):
> Takes an object and returns a reactive proxy of the original. This is equivalent to 2.x's Vue.observable().
> ... the returned proxy is ***not*** equal to the original object....
But currently when using `reactive` ***will*** change the original object.
***NOTE*** if someone could translate the chinese docs pls
Issue: #111

docs: added limitation documentation of using reactive

---

src/reactivity/reactive.ts
test/setup.spec.js

Make `__ob__` unenumerable to avoid stack overflow while some code traverse properties of reactive object internally like `vue-echarts` and `JSON.stringify()`.

fix: make __ob__ unenumerable

---

README.md
package.json
src/apis/lifecycle.ts
src/setup.ts
test/ssr/serverPrefetch.spec.js
yarn.lock

feat: add `onServerPrefetch`

---

src/component/component.ts
test/types/createComponent.spec.ts

fix #187 
As `never` is bottom type, `ExtractPropTypes<never>` is resolved as a type that accepts any field access:
```
ExtractPropTypes<never> = {
readonly [x: string]: undefined;
readonly [x: number]: undefined;
}
```
which is included in intersections of `ComponentRenderProxy` type, consists of `VueProxy` instance type.
The default type of `Props` seems to be `unknown`. As it is top type, `ExtractPropTypes<unknown>` will be `{}` which is expected type in this case.

fix: avoid accessing undeclared instance fields on type level

---

README.md
README.zh-CN.md
src/apis/computed.ts
src/apis/watch.ts
src/component/component.ts
src/component/index.ts
src/createElement.ts
src/helper.ts
src/index.ts
src/reactivity/reactive.ts
test/types/defineComponent.spec.ts

Since Vue `3.0.0-alpha.1`, `createComponent` has been renamed `defineComponent`.
See https://github.com/vuejs/vue-next/commit/1c4cdd841daa2ba9c1ec35068c92f1ae776cacea

refactor: rename createComponent as defineComponent

---

src/apis/lifecycle.ts

fix(lifecycle): deactivated should not run on onmounted lifecycle hook

---

.github/workflows/nodejs.yml

Removing node 8 since it's not longer supported

chore: remove node 8

---

src/install.ts
test/setup.spec.js

The parent setup should be called first, otherwise inject cannot get the provide data of the parent class

fix: the parent setup should be called first

---

src/apis/watch.ts
test/apis/watch.spec.js
test/templateRefs.spec.js

Adds `watchEffect` API to reflect the latest from the Vue 3 composition API ..
[https://github.com/vuejs/vue-next/commit/99a2e18c9711d3d1f79f8c9c59212880efd058b9](https://github.com/vuejs/vue-next/commit/99a2e18c9711d3d1f79f8c9c59212880efd058b9)
[https://github.com/vuejs/rfcs/commit/bbcc027a7e3b1df7bdfe647ca40437eeff2f92a3](https://github.com/vuejs/rfcs/commit/bbcc027a7e3b1df7bdfe647ca40437eeff2f92a3)
closes #271

feat(apis): add watchEffect API

---

src/reactivity/ref.ts

Same as vuejs/vue-next#614
We need special string or number types sometimes.
Ex. RelativePath, AbsolutePath
```typescript
type AbsolutePath = string & { __brand: unknown }
function readFile (path: AbsolutePath) {
// do some thing
}
function getAbsolutePath (path: string) {
if (path.startWith('file://')) return path as AbsolutePath
}
```
I use it for safe use translation keys,
but code is broken when passing UnwrapRef on vetur template interpolation.

types(reactivity): fix corner case on UnwrapRef

---

src/reactivity/ref.ts

Suppose I want to return ref to the template to be filled with my html element:
`const element = ref<HTMLElement>(null);`
Then I wrap it with reactive:
```
const state = reactive({
element,
...someOtherProps
})
```
Element goes through `UnwrapRef` and its type inference is broken.

type: Added Element type to ref BailTypes

---

src/apis/inject.ts

Fix(types): inject() return type - use undefined as return type instead of void

---

package.json
src/reactivity/ref.ts

I'm running into the problem where this type declared in my codebase:
```ts
export type GenericOption<T> = { name: string, value: T }
```
incorrectly `extends` `Ref`, which means that `UnwrapRef` is unwrapping it to `T` which isn't correct.
Here's a playground demonstrating this:
https://www.typescriptlang.org/play/?ssl=22&ssc=1&pln=22&pc=63#code/MYewdgzgLgBA+gJwKYDMBCCCGYAmAuGAVzAEsBHQpGCATwFsAjEAGxgF4YBlep5gCgCUAKCg0ADlUSoM2HOxiiJIFPGTosuIUgAeYkAlgkwUJAhSZgVAEqoAPABUAfDADeQmB5gB6LzGSYccGYaVWkNfFD1WQBud08AN0xmSgJ7WIBfISEjEzMLa1QAeTEoEnAHZzcPAHMkKEFU2I8IOoB+Pm1UgQJ4kBIcDKFgZkwICBgbFABJOjFmCpgSWeYkOiRjccmFqr8kAKCQqSjcAiOZXHkz8KaYMUIGZhJgGETkpABCRrjQSCgEQmAUH0fBcMFqUAANNQ6jB0gRJsVSuUnAJXHEPFAABYIEAAdxgYCQ+IAoggcQhBHFMpktLp9LBFFQAOLrUxPRFlMALDigsCYNYEaAIIzVKGvFIweywrKMyVIaDyFmE4XADnlbA0Zw6Ey4 …

Branding Ref so types with a value property aren't incorrectly unwrapped.

---

src/apis/watch.ts
test/apis/watch.spec.js

* watchEffect now  properly calls `runCleanup()` when the component unmounts.
* I applied the same change for "normal" watchers as I found that the bug applied to those as well.
Would like a second pair of eyes though, to verify.
close #293

fix(watch): component should runCleanup() on unmount

---

src/reactivity/ref.ts

resolve #257
Align with vue-next
https://github.com/vuejs/vue-next/blob/c6217b4d46cbd3d9e250f2f84de4846d3484c42d/packages/reactivity/src/ref.ts#L30-L37
~I am not sure how these lines work in our current codebase~
```ts
// with init value: a = ref({ a: ref(0) })
// typeof a will be Ref<{ a: number }>
export function ref<S, T = unknown, R = HasDefined<S> extends true ? S : RefValue<T>>(
raw: T
): Ref<R>;
```
~I kept it for now. But since it's not in vue-next, should we just remove it in order to have better type consistency with vue-next?~
**Edit**: Removed and it's exactly matched to vue-next now.

fix(type): fix incorrect ref unwrap

---

src/setup.ts
test/setup.spec.js

Binding function to the vm context.
Fixes: #144

fix: binding context vm when using function without parentheses 

---

src/apis/computed.ts

We use a Vue instancefor each computed(), as a helper to actually use Vue's `computed:` option.
However we don't destroy it when the host component is destroyed. When the computed property references reactive state that's external to the host instance, the helper instance stays in memory as it's watching the external state.
Properly destroying witht the host component fixes this.
fix #270

Fix(computed): destroy helper vm of computed to prevent memleak (fix #270)

---

CHANGELOG.md
package.json

Great thanks to @pikax for #311, making most of the APIs better aligned with the latest vue-next.
- The `lazy` option of `watch` has been replaced by the opposite `immediate` option, which defaults to false. (It's ignored when using the effect signature). [more details](https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md#breaking-changes-12) (#266)
- Rename `nonReactive` to `markRaw` 
- `UnwrapRef` types from `vue-next` this can cause some incompatibilities.
- Added missing reactivity API from vue-next, #311, @pikax 
- Fix return type of `toRefs`, #315, 
- Fix incorrect ref typing, #344, @antfu
- Binding context vm when using function without parentheses, #148, @pikax
- **computed**: destroy helper vm of computed to prevent memleak, #277, @LinusBorg 
- Added `unref`(#309), …

chore: release v0.6.0

---

src/component/componentProps.ts
test/types/defineComponent.spec.ts

fix #291 
Gets the correct type for the prop
Similar to https://github.com/vuejs/composition-api/pull/301
```ts
interface A {
a: String
}
defineComponent({
props: {
a: Object as PropType<A>
},
setup(props){
props.a 
}
})
```

types: Remove Function type from PropType type

---

.github/workflows/nodejs.yml
package.json
src/reactivity/ref.ts
test-dts/index.d.ts
test-dts/ref.test-d.ts
test-dts/tsconfig.build.json
test-dts/tsconfig.json
test-dts/watch.test-d.ts
tsconfig.json
yarn.lock

Added some of the dts testing (ref and watch) copied from vue-next. Will try to adopting more in the future.
This PR also updates Github Actions to using yarn and triggers dts tests.

feat(test): add dts testing

---

src/reactivity/reactive.ts
src/utils.ts
test/setup.spec.js

Fix for #231 - Ensure non reactive nulls are supported.
```
// 'this' cannot be set to null.
Object.hasOwnProperty.call(null, ''); // TypeError Cannot convert undefined or null to object
// Not an Object...
(null).hasOwnProperty('') // TypeError: Cannot read property 'hasOwnProperty' of null
```
Solution would be to check if the obj is null.

Handle non-reactive nulls (#231)

---

package.json
src/component/component.ts
src/component/componentProps.ts
test/types/defineComponent.spec.ts
yarn.lock

This continues #150, as it's kinda out-of-date. The type declarations are ported from vue-next.
Before
After

fix: defineComponent() with array props

---

src/reactivity/unwrap.ts
src/setup.ts
test/setup.spec.js

This unwraps nested refs on the template
NOTE: this needs to be intensively tested

fix(reactivity): unwrap nested refs on the template

---

package.json
rollup.config.js
src/reactivity/unwrap.ts
test/setup.spec.js
yarn.lock

fix: unwrapRefProxy native objects handling

---

src/component/componentProps.ts
test/types/defineComponent.spec.ts

before
after
Reapplied #352 to remove Function type from PropType type (removed by mistake in #364 ?) 
I have fix the test code also.

reapply #352 and fix test: Remove Function type from PropType type

---

src/reactivity/unwrap.ts
test/setup.spec.js

fix https://github.com/vuejs/composition-api/issues/379

fix(setup): call stack exceeded when returning circular dependency

---

src/install.ts
test/setup.spec.js

fix https://github.com/vuejs/composition-api/issues/151
Fix the bug when returning render function: `Vue.extend(Comp).extend({}) - vue-test-utils`
The bug is caused because we try to merge the `function` with an empty object.
https://github.com/vuejs/vue-test-utils/pull/1512 can be reopen and merged after we release this
also fix https://github.com/vuejs/vue-test-utils/issues/1484

fix(setup): returning `render` function breaks when extending with an empty object

---

src/reactivity/unwrap.ts
test/setup.spec.js

fix https://github.com/vuejs/composition-api/issues/384

fix: not unwrapping `markRaw` objects

---

src/setup.ts
test/setup.spec.js

fix https://github.com/vuejs/composition-api/issues/385
I have a few concerns here, because the unwrapping will create a new `object` everytime: 
```ts
const myObject = { a: 1}
const vm = new Vue({     data() {
return {
myObject,
}
},
}).$mount()
vm.myObject === myObject; // this will always be false
```
Not sure how much of a deal breaker this might be, one way to do this is only `unwrap` if there's a `ref` anywhere in the object.
The reason we create a new object is because we don't want to mutate the original object the user is using in the `setup`, because that will lead to some unexpected bugs

fix: unwrap refs returned by `data`

---

src/apis/watch.ts
test/v3/runtime-core/apiWatch.spec.ts

Fix https://github.com/vuejs/composition-api/issues/388
Prevent callback being called multiple times on the same callback

fix(watchEffect): prevent recursive calls when using `flush:sync`

---

README.md
src/setup.ts
test/setup.spec.js

Revert #387

---

README.md
README.zh-CN.md
package.json
scripts/update-readme.js

- Add the `browser` field to `package.json` for CDN services to auto resolving
- Updates the docs for guiding users to use versioned CDN packages
- Add a script to auto-update README on version bumping

docs: guide users to use versioned CDN

---

src/apis/computed.ts
src/apis/inject.ts
src/apis/lifecycle.ts
src/apis/watch.ts
src/createElement.ts
src/helper.ts
src/index.ts
src/runtimeContext.ts
src/setup.ts
test/setup.spec.js
test/setupContext.spec.js
test/templateRefs.spec.js
test/types/defineComponent.spec.ts
test/v3/runtime-core/apiLifecycle.spec.ts

Align with vue-next
chore: Renamed `getCurrentVM` to `getCurrentInstance` in the internal code. This should not affect on user side.

BREAKING CHANGE: rename createElement to h

---

src/index.ts
src/nextTick.ts
test/misc.spec.js

feat: export nextTick

---

src/setup.ts
test/setup.spec.js

fix(toRefs): do not warn when toRefs is called in a prop value

---

src/reactivity/unwrap.ts
test/setup.spec.js

fix(unwrapRef): copy __ob__ and make toRaw work in props

---

index.js
package.json
rollup.config.js

match with vue 2 naming style.
Now the dist file would look this:
cjs will import dev/prod version based on current env just acting the same behavior as vue. 
This should not affect regular users as the indexes in package.json changed as well.

BREAKING CHANGE: match dist file naming with vue 2

---

package.json
rollup.config.js
src/apis/inject.ts

Fix #422 
Webpack has a higher priority to resolve the `browser` field in package.json, which should not be a production build. Removing this will make it uses the "module" field in which the env will be handled by the bundler.q
https://github.com/vuejs/vue/blob/dev/package.json

fix: remove "browser" field in package.json

---

src/install.ts
src/runtimeContext.ts

By injecting and checking the flag on `Vue`, this should prevent multiple composition-api get installed to the same Vue constructor.
Fix #372.

fix: prevent multiple plugins get installed

---

src/install.ts

IE11 doesn't support `startsWith`, replaced it with array check.

fix(IE11): replace `startsWith` to be IE11 compatible

---

src/component/componentProps.ts
src/component/componentProxy.ts

- Omit some Vue attributes to override with our custom ones
- Fix `ExtractFunctionPropType` to accept general functions

fix(type): fix tying issues in #428

---

src/component/componentProps.ts
test-dts/defineComponent.test-d.ts
test-dts/index.d.ts

Fixed prop types becoming `any` or `undefined`.
- Reverted #444 because it changed some types of prop to `any` type
- Added tests to check whether it is not `any` type
- Fixed `Function` not to be `undefined` now it becomes `Function`
- Added tests to check whether it is not `undefined` type (of course it allows optional types)

fix PropType

---

README.md
README.zh-CN.md
src/apis/computed.ts
src/apis/state.ts
src/reactivity/index.ts
src/reactivity/reactive.ts
src/reactivity/ref.ts
src/utils/symbols.ts
test/apis/computed.spec.js
test/v3/reactivity/computed.spec.ts
test/v3/reactivity/readonly.spec.ts

Adding `shallowReadonly` and setting the `computed` to behave as `shallowReadonly`.
This will allow to check if we are allowed to set the value on the computed.
fix https://github.com/vuejs/composition-api/issues/445
This behaviour has not been approved nor in vue-next.
https://github.com/vuejs/vue-next/pull/1654 vue next PR

feat(shallowReadonly): add shallowReadonly and set computed to be shallowReadonly

---

src/reactivity/ref.ts
test-dts/ref.test-d.ts

fix https://github.com/vuejs/composition-api/issues/453
```ts
const STATUS_INITIAL = 'initial'
const STATUS_READY = 'ready'
const STATUS_INVALIDATING = 'invalidating'
type Status = 'initial' | 'ready' | 'invalidating'
const status = shallowRef<Status>(STATUS_INITIAL)
if (status.value === STATUS_READY) {
status.value = STATUS_INVALIDATING
}
```
Explanation `shallowRef<Status>` is returning `Ref<'initial'> |  Ref<'ready'> | Ref<'invalidating'>` so when you do 
```ts
if (status.value === STATUS_READY) {
// status === Ref<'ready'> 
}
```
Same as https://github.com/vuejs/vue-next/pull/1780

types: improve typings for `shallowRef`

---

src/reactivity/ref.ts

types: remove `Symbol.matchAll`

---

README.md
src/apis/watch.ts
test/apis/watch.spec.js

fix(watch): watch will trigger when added new keys using `set`

---

src/apis/watch.ts

fix #473 
I don't know what is causing this to happen, so I can't test this.
This should never happen because the `watcher.value` is still reactive but doesn't have `__ob__`

fix(watch): using deep:true in SSR context

---

README.md

Bundle size is often one of the first questions asked when deciding to add a dependency.
Added a bundle-size badge to advertise the small size.

docs: added minzipped size badge

---

README.md
src/install.ts
src/reactivity/reactive.ts
src/reactivity/ref.ts
src/utils/sets.ts
src/utils/symbols.ts
test/misc.spec.ts
test/v3/reactivity/reactive.spec.ts

Instead of changing `reactive` object we just use a weak set to keep track on what objects are reactive
This allows to have `arrays` as `reactive`, bringing it closer to vue 3
Still need to:
- Extensive testing
Close #501, close #219

feat: improve reactive checks

---

src/install.ts
src/runtimeContext.ts
test/helpers/create-local-vue.ts
test/use.spec.ts

fix #492
Need a better error message when replacing the VueConstructor,
I haven't tested but I don't think the plugin will play nice with multiple vue instances running at the same time.

feat: allow plugin to be installed in localVue

---

src/utils/sets.ts

Hey 👋🏻
The new version unfortunately breaks when using the composition API on server-side because of a missing check for `typeof window !== 'undefined'`.
This PR should add the check and avoid SSR errors 😋

fix(sets): check for window to avoid SSR errors

---

src/reactivity/reactive.ts
src/runtimeContext.ts

Allowing define `reactive` and `ref` before the `Vue.use`, the only caveat is when you have different `vue` versions installed. 
I think this is a pretty edge case and most of the time the user will use the version from `required('vue')`
> Note: would be nice to validate if reactive was used and if it was before the `Vue.use` and the `Vue.use` resolves to a different Vue constructor we could warn it
```js
// something like this
export function setVueConstructor(Vue: VueConstructor) {
if (__DEV__ && vueConstructor) {
warn('Another instance of vue installed')
}
if(__DEV__ && !vueConstructor && hasReactiveBeenUsed && vueConstructor !== vueDependency) {
warn('reactive was used globally with a different Vue instance, this might cause reactivity to fail')
}
vueConstructor = Vue …
```

feat(reactive): allow usage of reactive before `Vue.use`

---

src/apis/state.ts
src/install.ts
src/mixin.ts
src/reactivity/index.ts
src/reactivity/reactive.ts
src/reactivity/ref.ts
src/reactivity/set.ts
src/utils/instance.ts
src/utils/sets.ts
src/utils/symbols.ts
test/apis/state.spec.js
test/setup.spec.js

fix #517 
Simplifying the logic of `isReactive` now every valid reactive v2 object will be a valid isReactive object.
The only issue with this is `isReactive(obj) === true` won't mean auto-unwrapping 
```ts
const obj = Vue.observable({ a: ref(1) })
const reactiveObj = reactive({a: ref(1) })
isReactive(obj) // true
isReactive(reactiveObj) // true
obj.a // {value:1}
reactiveObj.a // 1
```

feat: making all vue2 reactive object be valid isReactive

---

src/runtimeContext.ts
test/use.spec.ts

fix(vue-test): prevent warning when using multiple `localVue`

---

src/component/componentOptions.ts

https://v3.vuejs.org/guide/component-custom-events.html#defining-custom-events
https://eslint.vuejs.org/rules/require-explicit-emits.html
> TIP
>
> It is recommended to define all emitted events in order to better document how a component should work.
Though it has no effects on Vue2, but we can still add `emits: string[] | Record<string, null | ((emitData: any) => boolean) >` in `defineComponent` for better documenting and to avoid eslint-plugin-vue@V7 throwing warnings.
Also, we have to warn people in readme that this has **no effects for validating the emit event** and just for smoothing the miragation.
---
Adding `emits` options will broke ThisType in defineComponent now.
while eslint will throw warnings if using `vue/require-explicit-emits`

fix: add emits options to defineComponent(fix #553)

---

src/runtimeContext.ts

fix: better `vueDependency` importing, close #564

---

README.md
src/apis/index.ts
src/reactivity/del.ts
src/reactivity/index.ts
src/reactivity/set.ts
src/utils/utils.ts
test/v3/reactivity/del.spec.ts

Workaround for notifying updates when removing keys in reactive objects and triggering view updates. Chinese README is missing.

feat(reactivity): add Vue.delete workaround

---

README.md
README.zh-CN.md

Hey 👋 
because the Vue 3 docs are out for a while already and cover the whole *composition API* topic well, it'd make more sense to link to them than to the RFC IMO. Thus the PR 😋

chore(README): point to v3 composition api docs

---

src/component/componentProxy.ts
test-dts/defineComponent.test-d.ts

types(defineComponent): fix options API support when using defineComponent

---

README.md
src/component/componentOptions.ts

Fix docs bug introduced by https://github.com/vuejs/composition-api/pull/595
```
ERROR in /home/user/github.com/VIAME-Web/client/platform/web-girder/views/ViewerLoader.vue(16,14):
16:14 Subsequent property declarations must have the same type.  Property 'refs' must be of type 'Data', but here has type '{ [key: string]: Element | Element[] | Vue | Vue[]; }'.
14 | declare module '@vue/composition-api' {
15 |   interface SetupContext {
> 16 |     readonly refs: { [key: string]: Vue | Element | Vue[] | Element[] }
|              ^
17 |   }
18 | }
19 | /**
```
Type of `refs` changed to unexported type `Data`.  I've verified that this change works on a local project.

docs: SetupContext.refs type, remove unnecessary docs

---

src/reactivity/reactive.ts
src/reactivity/readonly.ts

`shallowReactive` and `shallowReadonly` have only one argument, so `arguments.length === 2` is always `false`.

refactor: remove expressions that is always false

---

src/component/defineAsyncComponent.ts
src/component/index.ts
test-dts/defineAsyncComponent.test-d.ts
test/v3/runtime-core/apiAsyncComponent.spec.ts

This PR adds a implementation for defineAsyncComponent (I used code from the vue3 implementation) and returns a function async component as used in vue2 (see docs link). This should be a quite similar implementation as vue3 uses and should be compatible in most cases.
Some notes:
1. Tests are a copy of the vue3 tests an then modified.
2. ~Not shure of the typing of `Component` used `VueProxy<any,any>` but maybe there are better options~
3. Changed option suspensible  as vue2 has no suspense component
3. Helpfull docs:
* https://vuejs.org/v2/guide/components-dynamic-async.html#Handling-Loading-State
* https://v3.vuejs.org/api/global-api.html#defineasynccomponent

feat: add defineAsyncComponent API

---

src/reactivity/ref.ts

I found that `toRefs()` was unable to infer types from pinia (https://github.com/posva/pinia/discussions/406) but it works on Vue 3 so I adapted the type to the one existing in Vue 3: https://github.com/vuejs/vue-next/blob/master/packages/reactivity/src/ref.ts#L149 and it fixes the issue on pinia

fix(types): allow any object in toRefs

---

src/reactivity/reactive.ts
test/v3/reactivity/reactive.spec.ts

Keep consistent with `vue-next`:
https://github.com/vuejs/vue-next/blob/d3d9355c5a75675ab99ff8bb381e34d02e322e88/packages/reactivity/src/reactive.ts#L180-L185

fix(reactive): align behavior with vue-next

---

src/reactivity/reactive.ts
test/v3/reactivity/reactive.spec.ts

Keep consistent with vue-next:
https://github.com/vuejs/vue-next/blob/d3d9355c5a75675ab99ff8bb381e34d02e322e88/packages/reactivity/src/reactive.ts#L180-L185

fix(shallowReactive): align behavior with vue-next

---

src/utils/instance.ts
test/setup.spec.js

feat: add and delete object attributes would trigger update.

---

src/utils/instance.ts
test/setup.spec.js

fix: The behavior of development and production merge should be consistent.

---

README.md
README.zh-CN.md

Refs do not unwrap in a reactive array or nested array of a reactive object since 3.0.0-alpha.6 version. Hence, there are not limitations. See issue: https://github.com/vuejs/vue-next/issues/737

docs(README): update unwrap ref in an array limitations

---

README.md
README.zh-CN.md

The limitation text looks a bit confusing when you look at the sample code. The warning icon hanging at the end of the line looks strange. I've moved it to the next line and added an indent.

docs(README): synchronize limitation text and code sample

---

README.md

Sorry, in GitHub Markdown the icons are not aligned😅 Removed the extra indent and aligned the two icons

docs(README): remove extra indent

---

README.md

`**xx**` syntax dont work with html code

docs(README): use <b> tag to render bold font

---

src/apis/watch.ts
src/utils/utils.ts

This PR can solve the problem of not triggering `watch` callbacks in the following scenarios，keep the same behavior with vue-next.
```
<template>
<div id="app">
<div>{{ count[0] }}</div>
<button @click="change">jml</button>
</div>
</template>
<script>
import {watch,set, reactive} from '@vue/composition-api'
export default {
name: "App",  
setup() {
const count = reactive(["sdfs"])
const change = ()=>{
set(count, 0, "222")
}
watch(count,()=>{console.log("xxxxx");},{deep: true}
)
return {count,change};
},
};
</script>
<style>
#app {
font-family: Avenir, Helvetica, Arial, sans-serif;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
text-align: center;
color: #2c3e50;
margin-top: 60px;
}
</style>
```

fix(watch): align behavior with vue-next(doWatch).

---

src/utils/instance.ts
test/setup.spec.js

fix: #679 
In DEV mode, setup data in nextTick is proxied to vm._data. As a result, setup data is displayed after the component is updated.

fix(dev): setup data in nextTick is proxied to vm._data.

---

src/reactivity/set.ts
test/ssr/ssrReactive.spec.ts

fix #721
When using `set` if the object is not `reactive` it won't execute the unwrapping as per expected on a reactive object, in vue 2 every object used is expected to be `reactive` by default so I believe is safe to assume that if you calling `set` we will want to unwrap the value if is a `ref`

feat(reactivity): unwrap value when using `set`

---

src/reactivity/reactive.ts
test/v3/reactivity/reactive.spec.ts

fix(shallowReactive): should keep array as array

---

src/reactivity/reactive.ts
src/reactivity/readonly.ts
src/reactivity/ref.ts
test/v3/reactivity/readonly.spec.ts

fix(shallowReadonly): watch should work for ref/reactive with shallowReadonly

---

src/apis/watch.ts
test/apis/watch.spec.js

Fix: #418, align behavior with vue-next.

fix(watch): watched previous values can't be destructure on first fire.

---

src/reactivity/reactive.ts
test/setup.spec.js

fixes #715 
We should check the type of `__ob__` because in some cases it may be not an expected object, but, for example, a mock function, so the fact that `Boolean(!__ob__.__raw__) === true` does not necessarily indicate that the object is reactive

fix(reactivity): check type of __ob__ in isRaw and isReactive

---

README.zh-CN.md

use b tag insteads of markdown * syntax to  fix readme zh-CN version display error.

docs: use b tag insteads of markdown * syntax

---

src/reactivity/reactive.ts
src/reactivity/set.ts
test/ssr/ssrReactive.spec.ts

Solving #721 with #722：
```
it('result of #722', () => {
const state = { old: ref(false) }
set(state, 'new', ref(true))
expect(JSON.stringify(state)).toBe(
'{"old":{"value":false},"new":true}'  // 'old' is different from 'new'
)
})
```
the form of value of `old` key is different from `new` key.
if we solve #721 with recursive way:
```
it('solving with recursive way', () => {
const state = { old: ref(false) }
set(state, 'new', ref(true))
expect(JSON.stringify(state)).toBe(
'{"old":{"value":false},"new":{"value":true}}'
)
})
```
for above case, should `{"old":{"value":false},"new":{"value":true}}` is more appropriate? @pikax @antfu Look forward your comments？

fix(observe): solve the Ref not unwrapping on the ssr side issue with recursive way.

---

src/apis/inject.ts
src/reactivity/reactive.ts
src/reactivity/readonly.ts

refactor: use utils proxy insteads of Object.defineProperty

refactor: use utils proxy insteads of Object.defineProperty

---

test/v3/runtime-core/apiInject.spec.ts

test: test for provide/inject

---

test/v3/runtime-core/h.spec.ts

test: test for runtime/h

---

src/apis/watch.ts
test/apis/watch.spec.js
test/helpers/mockWarn.ts

fix(watch): errors thrown in the asynchronous callback function in watch will not be caught.

---

src/apis/watch.ts

fix(watch): only trigger warning in the dev environment

fix(watch): only trigger warning in the dev environment

---

src/apis/createElement.ts
src/apis/inject.ts
src/mixin.ts
src/utils/helper.ts

fix: only trigger warning in the dev environment

fix: only trigger warning in the dev environment

---

src/apis/watch.ts
test/v3/runtime-core/apiWatch.spec.ts

fix: [#752](https://github.com/vuejs/composition-api/issues/752)

fix(watch): traverse refs in deep watch

---

src/mixin.ts
test/setupContext.spec.ts

fix(customReactive): avoid circular reference.

---

src/reactivity/reactive.ts
test/ssr/ssrReactive.spec.ts

modify: ```mockReactivityDeep(value)----> mockReactivityDeep(value, seen)```

fix(mockReactivityDeep): add parameter seen for mockReactivityDeep.

---

src/apis/inject.ts
test/v3/runtime-core/apiInject.spec.ts

fix(runtime-core):  trigger warning when the injectionKey is undefined

---

src/mixin.ts
test/templateRefs.spec.js

fix: should dynamically update refs in context

---

src/apis/createElement.ts
src/apis/lifecycle.ts
src/apis/nextTick.ts
src/apis/watch.ts
src/reactivity/reactive.ts
src/reactivity/ref.ts
src/runtimeContext.ts

remove unnecessary type assertion

fix(type): remove unnecessary type assertion

---

src/apis/computed.ts
src/apis/effectScope.ts
src/apis/index.ts
src/apis/watch.ts
src/runtimeContext.ts
test/v3/reactivity/effectScope.spec.ts

Limitations:
- `scope.effects` is not equivalent with Vue 3, as there is not `effect` in Vue 2. It only stores nested `effectScope`.
- async function is not supported (could possibly introduce [`withAsyncContext`](https://github.com/vuejs/rfcs/blob/3478b0be65bb80e5d0eeb8fc54357e2445a84824/active-rfcs/0038-script-setup.md#top-level-await) from Vue 3.2, but with another PR).

feat: implement `effectScope` api

---

src/apis/computed.ts
src/apis/watch.ts
src/install.ts
src/mixin.ts
src/runtimeContext.ts

refactor: use utils isFunction

---

src/reactivity/ref.ts
test-dts/ref.test-d.ts
test/v3/reactivity/ref.spec.ts

align behavior with vue3
detail see: [vue3 #4162](https://github.com/vuejs/vue-next/pull/4162)

types: Simplify the SymbolExtract

---

src/reactivity/index.ts
src/reactivity/readonly.ts
src/reactivity/ref.ts

align behavior with vue3
details see : [vue3 #4194](https://github.com/vuejs/vue-next/pull/4194/files)

types: simplify the UnwrapNestedRefs

---

src/reactivity/index.ts
src/reactivity/readonly.ts
src/reactivity/ref.ts

In order to make vue-demi‘s vue(v2、v3) version better type alignment.
when vue/composition-api and vue-demi published new version , i can relatively easy to fix [vueuse #648 issue](https://github.com/vueuse/vueuse/issues/648)

chore(types): export UnwrapNestedRefs type

---

src/reactivity/reactive.ts

This fixes the codepen in the OP of #498 as well as in the application I'm working on.
I'm hoping it's valid to keep the internal value up-to-date rather than invoking the getter each time: I'm unable to prove that hypothesis wrong. It does assume that `getter` will return the last value passed to `setter`, but Vue 2's reactive getter/setters do that. I ran the tests with logging if they are different, and verified that situation never happens in the tests.
I believe infinite loops can still happen if you create a reactive object directly (`reactive()` or `set()`) or indirectly (`obj.x = {}`) but this PR solves most of it.
Fixes #498

fix: don't invoke Vue getters in setter

---

README.md

I do not know if there is an inner logic in putting this limitation under the "ref" header, but I got very confused because I expected this limitation under "reactive" since it involves the reactive function.

docs: moving set and del warning to the reactive block

---

src/apis/watch.ts
test/apis/watch.spec.js

fix(watch): always triggers when watching multiple refs

---

README.md

This plugin relies on Typescript "Recursive Type Aliases" improvement, which was  released with Typescript 3.7:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#more-recursive-type-aliases
If used with Typescript 3.5.1 (the version specified in docs), typescript would throw the following error:
```
251:14 Type alias 'DeepReadonly' circularly references itself.
249 | declare type Primitive = string | number | boolean | bigint | symbol | undefined | null;
250 | declare type Builtin = Primitive | Function | Date | Error | RegExp;
> 251 | declare type DeepReadonly<T> = T extends Builtin ? T : T extends Map<infer K, infer V> ? ReadonlyMap<DeepReadonly<K>, DeepReadonly<V>> : T extends ReadonlyMap<infer K, infer V> ? ReadonlyMap<DeepReadonly<K>, DeepReadonly<V>> : T …
```

docs: Update required typescript version

---

src/apis/watch.ts
test/v3/runtime-core/apiWatch.spec.ts

close #805 
I personally think that the combination of the `Reactivity` API with the `Watch` API provides great flexibility, but also leads to very complex boundary condition handling, so perhaps the best we can do now is to find and solve problems to achieve higher test coverage～

fix(api-watch): watching nested ref array w/ deep doesn't work

---

package.json

Right now you can't `import {watch} from "@vue/composition-api"` in nodejs from a `.mjs` file. If you try that, you'll get:
```
file:///Users/caleb/Code/temp/x.mjs:1
import {ref} from "@vue/composition-api";
^^^
SyntaxError: Named export 'ref' not found. The requested module '@vue/composition-api' is a CommonJS module, which may not support all module.exports as named exports.
```
I think since there's no `"type"` in package.json, the default module type for any `.js` is CJS. The files in the red and the green appear to be identical so I think this is low-risk and the right way to do it. As I understand it Webpack will parse anything, it doesn't really have a concept of module type, and not sure about other bundlers.

fix: importing from esm in node

---

src/component/componentProps.ts
test-dts/defineComponent.test-d.ts

fix: correct prop type inference when using PropType<unknown>

---

README.md
src/apis/computed.ts
src/apis/watch.ts
src/reactivity/index.ts
src/reactivity/ref.ts
test/apis/computed.spec.js

Add an `effect` property on computed to differentiate them from refs
---
Another possible implementation is to keep the computed types where they were and add an option effect to ref

feat(computed): allow differentiating refs from computed

---

src/reactivity/ref.ts
test/v3/reactivity/ref.spec.ts

fix [#817](https://github.com/vuejs/composition-api/issues/817)

fix(proxyRefs): When using proxyRefs, the internal variable composition-api.refKey is exposed on the object itself #817

---

src/reactivity/reactive.ts
src/reactivity/set.ts
test/ssr/ssrReactive.spec.ts

Same as #795 
It seems to still be failing.
It creates https://github.com/posva/pinia/issues/648

fix(ssr): `set()` twice lose reactivity

---

src/runtimeContext.ts

Resolves https://github.com/vuejs/composition-api/issues/827
This PR adds compatibility support for `vm.type`.

fix: add `type` to component instance

---

src/component/componentOptions.ts
src/component/defineComponent.ts
test/types/defineComponent.spec.ts

see https://github.com/vuejs/vue-next/blob/140f08991727d7c15db907eea5a101979fe390b2/packages/runtime-core/src/apiDefineComponent.ts#L95-L120
```ts
// overload 2: object format with no props
// (uses user defined props interface)
// return type is for Vetur and TSX support
export function defineComponent<
Props = {},
RawBindings = {},
D = {},
C extends ComputedOptions = {},
M extends MethodOptions = {},
Mixin extends ComponentOptionsMixin = ComponentOptionsMixin,
Extends extends ComponentOptionsMixin = ComponentOptionsMixin,
E extends EmitsOptions = EmitsOptions,
EE extends string = string
>(
options: ComponentOptionsWithoutProps<
Props,
RawBindings,
D,
C,
M,
Mixin,
Extends,
E,
EE
>
): DefineComponent<Props, RawBindings, D, C, M, Mixin, Extends, E, EE>
```
Vue 3 use `{}` rather than …

fix(types): defineComponent object format with no props type

---

src/mixin.ts
src/utils/instance.ts
src/utils/vmStateManager.ts
test/setup.spec.js

fix https://github.com/vuejs/composition-api/issues/840
This problem is triggered when the user installs the composition API and uses the template method to define that the key of data contains attrs
Like test case description

fix: changing prop causes rerender to lose attributes #840

---

src/apis/createApp.ts

This way, `App` type is compatible with Vue 3 while being backwards compatible

feat(types): allow a generic in App type

---

src/reactivity/ref.ts
test/apis/computed.spec.js

fix(toRef): issue #855

---

README.zh-CN.md

docs: update Chinese docs

---

src/mixin.ts

`isPlainObject` is too strict for the returning value of setup function. Sometimes user may `return { ...refs }` in setup function, and `Symbol(Symbol.toStringTag) in refs` (eg: refs is a ESModule object), then `{ ...refs }` will inherit that symbol property, then `isPlainObject({ ...refs }) === false` which may not that intuitive.
Besides, vue3 use `isObject` too. https://github.com/vuejs/vue-next/blob/87c86e4cc2/packages/runtime-core/src/component.ts#L688

fix: #874 setup return object with type of Module

---

src/runtimeContext.ts

微前端架构下，子应用重复注册 composition-api 插件失败，导致插件提供的响应式 API 不可用

fix: improve register check, close #876

---

src/component/componentOptions.ts
src/runtimeContext.ts
test-dts/defineComponent-vue2.d.tsx

If you define a component with `emits`, then you can type this.$emits
So with this, you get autocompletion and signature validation on `this.$emit`
```ts
defineComponent({
emits: {
click: (n: number) => typeof n === 'number',
input: (b: string) => b.length > 1,
},
created() {
this.$emit('click', 1)
this.$emit('input', 'foo')
},
})
```
but you don't get the same behavior in the setup function.
```ts
defineComponent({
emits: {
click: (n: number) => typeof n === 'number',
input: (b: string) => b.length > 1,
},
setup(props, { emit ) {
emit('click', 1)
emit('input', 'foo')
},
})
```
this will work, gives no errors, but also no auto completion or compilation safety with typescript.
This PR is will enable that, so that the emit property of the SetupContext has typed emits.
I don't know if there …

fix(types): `emit` type in SetupContext

---

src/reactivity/force.ts
src/reactivity/reactive.ts
src/reactivity/ref.ts
test/v3/reactivity/ref.spec.ts

Hi, I found another situation that's causing me infinite loops with this library but not with Vue 3

fix(shallowReactive): don't trigger watchers for oldVal === newVal

---

src/mixin.ts
src/utils/instance.ts
test/templateRefs.spec.js

#764 works perfectly when you're using normal slots, but not if you forward scoped slots to a child component.
Unfortunately, and I hope I'm mistaken about this, every component's entire VNode tree has to be iterated to find a component that needs refs updated.
Here's some perf testing of this PR in our application. In the Firefox profiler, `afterRender` shows up for:
* 0.5ms in a 1,000-node component
* 15ms in a 50,000-node component
Ideally this would use Vue's patch hooks like native Vue 2 refs do. Would it be out of the question to introduce a faster `v-ref=` instead of this PR? Or is this fast enough given that the readme already warns about performance issues?

fix: dynamically update deep scopedSlot refs

---

src/apis/watch.ts
test/apis/watch.spec.js

Currently `watch` with `deep:true` will ignore object that marked with `markRaw`.
This fix makes it align with the latest [vue3 behavior](https://codesandbox.io/s/lucid-rgb-z2h0x?file=/src/App.vue).

fix: markRaw in watch

---

src/component/componentProps.ts

Ported from [vue-next](https://github.com/vuejs/core/blob/5898629d723e82b68e9b17b91bf8b1a8390a3912/packages/runtime-core/src/componentProps.ts#L91)
Volar show type error for missing optional boolean without this.

fix(types): optional Boolean props as default props

---

src/apis/watch.ts
test-dts/watch.test-d.tsx
test/v3/runtime-core/apiWatch.spec.ts

with [https://github.com/vuejs/core/pull/2425](https://github.com/vuejs/core/pull/2425)
maybe break change

types(watch): watch array callback params type tuples

---

src/reactivity/reactive.ts

`let val = obj[key]` have already triggerd the getter; So `const value = getter ? getter.call(obj) : val` is redundant

refactor: obj[key] have already triggered the getter

---

src/reactivity/reactive.ts

We now use Vue Demi to work, such as using variables named at the beginning of `$`to skip the reactive. 
I think we should keep the same raw key as vue3
https://github.com/vuejs/core/blob/4a3237ad9300693e465f82a6be3552565a1c4be3/packages/reactivity/src/reactive.ts#L17

feat: Unified as the key of raw in vue3

---

src/apis/createElement.ts

resolve https://github.com/vuejs/composition-api/issues/804
Have no idea but let h can bind vm returned by getCurrentInstance in setup

feat(createElement): allow createElement to bind vm

---

src/apis/createElement.ts
test/v3/runtime-core/h.spec.ts

#804   Manually spcifying instance is supported
Vueuse can add a function to make the call easier

test: add tests for createElement with binding

---

src/utils/instance.ts

in `uni-app` case, `_vnode` may be `null`
issue: https://github.com/dcloudio/uni-app/issues/3295

fix: nullish check for vnode

---

src/apis/watch.ts
test-dts/watch.test-d.tsx
test/v3/runtime-core/apiWatch.spec.ts

resolve https://github.com/vuejs/composition-api/issues/924

fix(type): align watch types with vue3

---

src/apis/inject.ts
test/apis/inject.spec.js
test/v3/runtime-core/apiInject.spec.ts

Matches vue 3's implementation on provide/inject where passing `undefined` as a defaultValue silences the error
https://github.com/vuejs/core/pull/894/files

fix(inject): allow default value to be undefined

---

src/apis/createApp.ts
test/createApp.spec.ts

https://vuejs.org/guide/components/provide-inject.html#app-level-provide
Inspired by @skyline0705

feat: support Vue3 style app-level provide

---

src/reactivity/ref.ts

Add `Date` to BaseTypes to prevent type resolve mismatch.
```
Argument of type 'string | { toString: () => string; toDateString: () => string; toTimeString: () => string; toLocaleString: { (): string; (locales?: string | string[] | undefined, options?: DateTimeFormatOptions | undefined): string; }; ... 38 more ...; toJSON: (key?: any) => string; }' is not assignable to parameter of type 'string | Date'.```

fix(types): add `Date` to `BaseTypes`

---

package.json

Resolve type inference problem when `moduleResolution` is  `NodeNext`.
https://stackblitz.com/edit/typescript-jldbyo?file=tsconfig.json,index.ts,package.json

fix(types): add types to package export

---

src/component/componentProps.ts

fix prop type is Function, but setup function infer to a never type.
[issue link](https://github.com/vuejs/composition-api/issues/971)

fix(types): function constructor should be a Function
